export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PROFILE_CREATED = "PROFILE_CREATED";
export const CHANGE_THEME = "CHANGE_THEME";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const SEARCH_PROFILES = "SEARCH_PROFILES";
export const SEARCH_FOR_EMAIL = "SEARCH_FOR_EMAIL";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const NOTIFICATIONS_LOADING = "NOTIFICATIONS_LOADING";

export const GET_FRIENDS = "GET_FRIENDS";
export const FRIENDS_LOADING = "FRIENDS_LOADING";
export const ADD_FRIEND = "ADD_FRIEND";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const ACCEPT_FRIEND = "ACCEPT_FRIEND";

export const GET_POSTS = "GET_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const GET_FRIEND_POSTS = "GET_FRIEND_POSTS";
